manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Amos698
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feature-test
      import: app/west.yml
  self:
    path: config
